file_type: csv
dataset_name: Players_Info_2024
file_name: /kaggle/input/indian-premier-league-ipl-2008-2024/Players_Info_2024
table_name: players_info
inbound_delimiter: ","
outbound_delimiter: "|"
skip_leading_rows: 1
columns: 
    - player_name
    - team_name
    - player_nationality
    - date_of_birth
    - player_role
    - ipl_debut
    - about
    - batting_style
    - bowling_style
    - player_salary
