file_type: csv
dataset_name: team_performance_dataset_2008_to_2024
file_name: /kaggle/input/indian-premier-league-ipl-2008-2024/team_performance_dataset_2008to2024
table_name: team_performance
inbound_delimiter: ","
outbound_delimiter: "|"
skip_leading_rows: 1
columns: 
    - match_id
    - date
    - teams
    - venue
    - toss_winner
    - toss_decision
    - match_winner
    - win_type
    - win_margin
    - first_innings_score
    - umpire
    - powerplay_scores
    - middle_overs_scores
    - death_overs_scores
    - umpire1
    - umpire2
    - player_of_match
    - second_innings_score
